///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
@isTest(seealldata = true)
private class testQAEmail {
    
    private class RestMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            String fullJson = 'Response';
            
            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'text/json');
            res.setBody(fullJson);
            res.setStatusCode(200);
            return res;
        }
    }
    
    static testMethod void testQAEmail() {          
        
        Account a = new Account(Name = 'AccountTest');
        insert a;       
        
        Contact cont = new Contact(firstname = 'John', lastname = 'Smith2524', AccountID =a.Id, email='Hello123@goodbye.com');
        insert cont;
        
        Case cas = new Case(ContactID = cont.id, 
                            Status = 'New', Origin = 'Phone');
        insert cas;
        
        EmailMessage[] newEmail = new EmailMessage[0]; 
        
        newEmail.add(new EmailMessage(FromAddress = 'test@abc.org', Incoming = True, 
                                      ToAddress= 'hello@670ocglw7xhomi4oyr5yw2zvf.8kp7yeag.8.case.salesforce.com', 
                                      Subject = 'Test email', TextBody = '23456 ', ParentId = cas.Id)); 
        
        insert newEmail;    
        
        List<String> lstEM = new List<String>();
        string EMID = newEmail[0].ID;
        
        lstEM.add(EMID);    
        clarificationEmailHandler.closeClariHandler(lstEM);
        
        ID caseID = cas.ID;
        
        Test.setMock(HttpCalloutMock.class, new RestMock());
        Test.startTest();       
        QuickAction.SendEmailQuickActionDefaults sendEmailDefaults = test.newSendEmailQuickActionDefaults(caseId, null);
        
        support.EmailTemplateSelector cntl;
        List<QuickAction.QuickActionDefaults> defaults = new List<QuickAction.QuickActionDefaults>();
        EmailPublisherForHighPriorityCases e = new emailpublisherforhighprioritycases();
        
        //e.onInitDefaults(defaults);
        //mailmsg.onInitDefaults(defaults );
        //cntl.onInitDefaults(defaults);
        Test.stopTest();
        //EmailMessage emailMessage = (EmailMessage) sendEmailDefaults.getTargetSObject();
        //System.assertNotEquals(null, emailMessage);
        
    }
    
    //Added by Himanshu Rana for testing Email Message Cloning
    @isTest
    static void emailCloningTest()
    {
        Account a = new Account(Name = 'AccountTest');
        insert a;       
        
        Contact cont = new Contact(firstname = 'John', lastname = 'Smith2524', AccountID =a.Id, email='Hello12390@goodbye.com');
        insert cont;
        
        Case winnerCase = new Case(ContactID = cont.id, 
                                   Status = 'Working', Origin = 'Phone', Subject = 'Winner Case');
        insert winnerCase;
        
        Case retrievedWinnerCase = [SELECT Id, CaseNumber, Subject, Description, ParentId FROM Case WHERE Id = :winnerCase.Id];
        
        Case looserCase = new Case(ContactID = cont.id, 
                            Status = 'Merged - Duplicate', Origin = 'Phone', Subject = 'Merged Case', Merged_Parent_Case__c = retrievedWinnerCase.CaseNumber);
        insert looserCase;
        
        Case retrievedlooserCase = [SELECT Id, CaseNumber, Subject, Description, Merged_Parent_Case__c FROM Case WHERE Id = :looserCase.Id];
        /*
        CaseComment comment = new CaseComment();
        comment.CommentBody = 'Case ' +  retrievedlooserCase.CaseNumber + ' has been merged with Case ' + retrievedWinnerCase.CaseNumber +'.';
        comment.ParentId = retrievedlooserCase.Id;
        insert comment;*/
        
        EmailMessage email = new EmailMessage(
            Subject = 'Test Email',
            TextBody = 'This is a test email',
            ToAddress = 'test@example.com',
            ParentId = retrievedlooserCase.Id
        );
        
        Test.setMock(HttpCalloutMock.class, new RestMock());
        Test.startTest();
        insert email;
        Test.stopTest();
    }
}
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////