public without sharing class UnlockApproval{

/*

    @InvocableMethod
    public static void unlockInvocable(list<Marketing_Projects__c> lstMP){
    
        List<Marketing_Projects__c> lstUpdMP = new List<Marketing_Projects__c>();
    
        For(Marketing_Projects__c mp : lstMP){
            
            Boolean isLocked = Approval.isLocked(mp);
        
            if(isLocked){
                lstUpdMP.add(mp);    

            }
            
            isLocked = False;
        }
        
        if(lstUpdMP.size()> 0){
            Approval.UnlockResult[] lrList = Approval.unlock(lstUpdMP, false);     
        }           
    }    
    */
}